repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.12
        exclude: |
          migrations/.*\.py$
          | tests/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: [
          "--max-line-length=88",
          "--extend-ignore=E203,E501,W503"
        ]
        exclude: |
          migrations/.*\.py$
          | tests/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: |
          migrations/.*\.py$
          | tests/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
