name: Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env from .env.example
        run: cp .env.example .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test container
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml build test

      - name: Run tests with Docker Compose
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test

      - name: Shutdown services
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down -v
